parameters:
#    monistix_organization.example.class: Monistix\OrganizationBundle\Example

services:
#    monistix_organization.example:
#        class: %monistix_organization.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
