<?php

/**
 * BaseCompany
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property boolean $enabled
 * @property string $notes
 * @property Doctrine_Collection $Companies
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method boolean             getEnabled()   Returns the current record's "enabled" value
 * @method string              getNotes()     Returns the current record's "notes" value
 * @method Doctrine_Collection getCompanies() Returns the current record's "Companies" collection
 * @method Company             setName()      Sets the current record's "name" value
 * @method Company             setEnabled()   Sets the current record's "enabled" value
 * @method Company             setNotes()     Sets the current record's "notes" value
 * @method Company             setCompanies() Sets the current record's "Companies" collection
 * 
 * @package    monistix
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompany extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('enabled', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('notes', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Project as Companies', array(
             'local' => 'id',
             'foreign' => 'company_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}