<?php

/**
 * BaseServer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $hostname
 * @property integer $group_id
 * @property boolean $enabled
 * @property string $notes
 * @property ServerGroup $ServerGroup
 * 
 * @method string      getName()        Returns the current record's "name" value
 * @method string      getHostname()    Returns the current record's "hostname" value
 * @method integer     getGroupId()     Returns the current record's "group_id" value
 * @method boolean     getEnabled()     Returns the current record's "enabled" value
 * @method string      getNotes()       Returns the current record's "notes" value
 * @method ServerGroup getServerGroup() Returns the current record's "ServerGroup" value
 * @method Server      setName()        Sets the current record's "name" value
 * @method Server      setHostname()    Sets the current record's "hostname" value
 * @method Server      setGroupId()     Sets the current record's "group_id" value
 * @method Server      setEnabled()     Sets the current record's "enabled" value
 * @method Server      setNotes()       Sets the current record's "notes" value
 * @method Server      setServerGroup() Sets the current record's "ServerGroup" value
 * 
 * @package    monistix
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('server');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('hostname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('enabled', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('notes', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ServerGroup', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}