<?php

/**
 * BaseProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $organization_id
 * @property boolean $enabled
 * @property string $notes
 * @property Organization $Organization
 * @property Doctrine_Collection $Projects
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method integer             getOrganizationId()  Returns the current record's "organization_id" value
 * @method boolean             getEnabled()         Returns the current record's "enabled" value
 * @method string              getNotes()           Returns the current record's "notes" value
 * @method Organization        getOrganization()    Returns the current record's "Organization" value
 * @method Doctrine_Collection getProjects()        Returns the current record's "Projects" collection
 * @method Project             setName()            Sets the current record's "name" value
 * @method Project             setOrganizationId()  Sets the current record's "organization_id" value
 * @method Project             setEnabled()         Sets the current record's "enabled" value
 * @method Project             setNotes()           Sets the current record's "notes" value
 * @method Project             setOrganization()    Sets the current record's "Organization" value
 * @method Project             setProjects()        Sets the current record's "Projects" collection
 * 
 * @package    monistix
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('organization_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('enabled', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('notes', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organization', array(
             'local' => 'organization_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ServerGroup as Projects', array(
             'local' => 'id',
             'foreign' => 'project_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}