<?php

/**
 * PluginTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Plugin');
    }
}