<?php

/**
 * ServerGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServerGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServerGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServerGroup');
    }

    public function getWithServers() {

	    $q = $this->createQuery('g')
		    ->leftJoin('g.Servers s');

	    return $q->execute();
    }
}
