parameters:
#    acme_hello.example.class: Acme\HelloBundle\Example

services:
#    acme_hello.example:
#        class: %acme_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
