Organization:
        actAs: { Timestampable: ~ }
        columns:
                name: { type: string(255), notnull: true }
                enabled: { type: boolean, notnull: true, default: true }
                notes: { type: string }
 
Project:
        actAs: { Timestampable: ~ }
        columns:
                name: { type: string(255), notnull: true }
                organization_id: { type: integer, notnull: true }
                enabled: { type: boolean, notnull: true, default: true }
                notes: { type: string }
        relations:
                Organization: { onDelete: CASCADE, local: organization_id, foreign: id, foreignAlias: Organizations } 

Server:
        actAs: { Timestampable: ~ }
        columns:
                name: { type: string(255), notnull: true }
                hostname: { type: string(255), notnull: true }
                group_id: { type: integer, notnull: true }
                enabled: { type: boolean, notnull: true, default: true }
                notes: { type: string }
        relations:
                ServerGroup: { onDelete: CASCADE, local: group_id, foreign: id, foreignAlias: Servers } 
                

ServerGroup:
        actAs: { Timestampable: ~ }
        columns:
                name: { type: string(255), notnull: true }
                project_id: { type: integer, notnull: true }
                enabled: { type: boolean, notnull: true, default: true }
                notes: { type: string }
        relations:
                Project: { onDelete: CASCADE, local: project_id, foreign: id, foreignAlias: Projects } 

Plugin:
        actAs: { Timestampable: ~ }
        columns:
                name: { type: string(255), notnull: true }
                enabled: { type: boolean, notnull: true, default: true }
                notes: { type: string }
